### ISSUE TITLE
ModuleNotFoundError: No module named 'PLS'

### ISSUE THREAD

**Issue by luke1879012** [plenoi/SAPPHIRE#1]
Unable to run the program properly

Error details：
Traceback (most recent call last):
  File "D:/_code/_github/SAPPHIRE/sapphire.py", line 371, in <module>
    allclf = load("./model/allclfs.sav")
  File "D:\_code\_github\SAPPHIRE\venv\lib\site-packages\joblib\numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "D:\_code\_github\SAPPHIRE\venv\lib\site-packages\joblib\numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "D:\_software\Python\Python36\lib\pickle.py", line 1050, in load
    dispatch[key[0]](self)
  File "D:\_software\Python\Python36\lib\pickle.py", line 1338, in load_global
    klass = self.find_class(module, name)
  File "D:\_software\Python\Python36\lib\pickle.py", line 1388, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'PLS'

The Python interpreter is 3.6
The following instructions were executed:
```
pip install scikit-learn==0.24.1
pip install pandas
```

**Comment by jetu20** [comment]
I also encounter similar issues

**Comment by plenoi** [comment]
really sorry we will fix that today !!

 

respect

Phasit

 
 

Sent: Wednesday, June 29, 2022 at 2:09 AM

**Comment by plenoi** [comment]
Fix it !!
