### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by PaabloFdeez** [plenoi/SAPPHIRE#2]
Hello, 

During the last few days I have been trying to use your code in order to analyze the thermophilicity for a set of proteins, I have followed the instructions proposed both for sapphire and those indicated for sapphire. It is in the last step, at the time of executing sapphire.py when I get the following error:

`Traceback (most recent call last):
  File "sapphire", line 380, in <module>
    fasta = read_fasta('/home/sie/TFM_pablo/uniref50/uniref50.fasta')
  File "scriptpssm", line 10, in read_fasta
    fasta = [[item[0], re.sub('[^ACDEFGHIKLMNPQRSTVWY]', '', ''.join(item[1:]).upper())] for item in line2]
  File "scriptpssm", line 10, in <listcomp>
    fasta = [[item[0], re.sub('[^ACDEFGHIKLMNPQRSTVWY]', '', ''.join(item[1:]).upper())] for item in line2]
IndexError: list index out of range
`

I am not sure what may be the problem causing it, thank you in advance.

**Comment by plenoi** [comment]
Hi,

 

Did you change something in sapphire.py ?   the error tell me like it cannot read fasta file.

is your fasta file has the same format as seq.fasta.  can you send me your input file ?

 

Phasit 

 
 

Sent: Saturday, August 05, 2023 at 10:40 PM
From: "PaabloFdeez" ***@***.***>
To: "plenoi/SAPPHIRE" ***@***.***>
Cc: "Subscribed" ***@***.***>
Subject: [plenoi/SAPPHIRE] List index out of range (Issue #2)


 

Hello,

During the last few days I have been trying to use your code in order to analyze the thermophilicity for a set of proteins, I have followed the instructions proposed both for sapphire and those indicated for sapphire. It is in the last step, at the time of executing sapphire.py when I get the following error:

Traceback (most recent call last): File "sapphire", line 380, in <module> fasta = read_fasta('/home/sie/TFM_pablo/uniref50/uniref50.fasta') File "scriptpssm", line 10, in read_fasta fasta = [[item[0], re.sub('[^ACDEFGHIKLMNPQRSTVWY]', '', ''.join(item[1:]).upper())] for item in line2] File "scriptpssm", line 10, in <listcomp> fasta = [[item[0], re.sub('[^ACDEFGHIKLMNPQRSTVWY]', '', ''.join(item[1:]).upper())] for item in line2] IndexError: list index out of range 

I am not sure what may be the problem causing it, thank you in advance.

**Comment by PaabloFdeez** [comment]
I think I made a mistake when using the seq.fasta file, in my case, I am using the fasta file provided by pssmpro, I mean the uniref50.fasta file. If this is not the file, which one should I use?

Thanks again.
